### ISSUE TITLE
[DL] TODO

### ISSUE THREAD

**Issue by Eygle** [Eygle/EygleServer#1]
- [x] Refactoring
   - [x] Angular Material
   - [x] Typescript
   - [x] Node.js
   - [x] Mongodb ?
- [ ] Account & password protected
- [ ] All extracted  mediafiles in db (cron)
- [ ] Extract info from files name (movies/series/misc/all)
- [ ] Get link(s)
- [ ] Stats DL/co/etc
- [ ] Shortcuts (delete/copy link, ...)
- [ ] DL (smart)
- [ ] Zip => DL (smart)
- [ ] Categories (Movies, etc.)
- [ ] When info: image + last files by name/date/info
- [ ] TV Show
   - [ ] Image
   - [ ] Title
   - [ ] Season/Episode nbr
   - [ ] Episode name
   - [ ] quality/size
- [ ] Movies
   - [ ] Image
   - [ ] Title (fr/vo)
   - [ ] Quality (HDRip, etc.)
- [ ] Misc
   - [ ] Get kulti links
   - [ ] Force download (button)
   - [ ] Streaming ?
   - [ ] Identify media
